### ISSUE TITLE
Implement a method to make the command console only or ingame only

### ISSUE THREAD

**Issue by lukeeey** [CortexPE/Commando#8]
Something like `$cmdCtx->setAllowConsole(true)`. This would require a new error message and error code

**Comment by CortexPE** [comment]
Shouldn't you do it yourself?
https://github.com/CortexPE/Hierarchy/blob/master/src/CortexPE/Hierarchy/command/HierarchySubCommand.php#L66-L68

then just do the check on your command's onRun

because, there might be some instances where you'd want it to ONLY be in game or on console if the arguments satisfy a certain condition... doing this would limit that.

**Comment by thebigsmileXD** [comment]
It would be really useful to have this inside the virion already. Firstly, to remove console-only commands from player clients, secondly to reduce duplicated code. Check out https://github.com/JorelAli/1.13-Command-API/tree/master/1.13CommandAPI/src/io/github/jorelali/commandapi/api tor reference. Iirc, it allows setting who can use the command.
